CREATE TABLE USER_GRP (
	USER_GRP_NUM INT PRIMARY KEY AUTO_INCREMENT,
    USER_GRP_NM VARCHAR(20) NOT NULL,
    USER_GRP_DESC TEXT
);

CREATE TABLE USER (
	USER_NUM INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(30) NOT NULL,
    USER_PW VARCHAR(30) NOT NULL,
    USER_GRP_NUM INT NOT NULL,
    POSS_TOKEN_QTY INT,
    FOREIGN KEY (USER_GRP_NUM) REFERENCES USER_GRP (USER_GRP_NUM)
);



